name: Train Machine Learning Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training script
      run: |
        python Scripts/train.py

    - name: Commit model (Optional)
      run: |
        # If you want to save and commit your trained model
        # For example, saving the model with joblib
        python -c 'import joblib; model = joblib.load("your_model.pkl"); joblib.dump(model, "saved_model.pkl")'

    - name: Upload trained model (Optional)
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: saved_model.pkl

    - name: Clean up
      run: |
        # Perform any cleanup if needed
        rm -rf .venv
