name: MLflow Model Training and Logging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-test-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train the model and log metrics
      env:
        MLFLOW_TRACKING_URI: file:///tmp/mlruns  # Log metrics locally in runner's filesystem
      run: python Scripts/train.py

    - name: Test the model and log test metrics
      env:
        MLFLOW_TRACKING_URI: file:///tmp/mlruns  # Log metrics locally in runner's filesystem
      run: python Scripts/test.py

    - name: Upload MLflow Logs as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-logs
        path: /tmp/mlruns   # Ensure this path is correct
